### ISSUE TITLE
Does Not Communicate with JabRef, New Instance Started (Linux,FF)

### ISSUE THREAD

**Issue by PorcelainMouse** [JabRef/JabRef-Browser-Extension#111]
When I click on the JabFox icon, a new instance of JabRef is started, which complains about backup files for .bib files that were open.  I'm assuming this is incorrect behavior.  JabFox Add-On shows communication with JabRef is successful, prior.

jabref-5.0.30001-1.x86_64
FF 70

**Comment by tobiasdiez** [comment]
This sounds like a bug of JabRef itself. Usually it should only show this warning if you didn't properly closed the last instance. Maybe this was a result of your previous testing?

If you can reproduce it, then please report it at https://github.com/JabRef/jabref (this rep here is for browser-addon-specific issues).

**Comment by LyzardKing** [comment]
@tobiasdiez This is the same issue that I have.
In the previous issue that I opened on the jabref repo the new instance would open a blank tab,
with your commits noted on that issue the new window opens the correct tab (with the proper .bib file).
The backup warning is opened because there is another instance open

**Comment by tobiasdiez** [comment]
Ah ok... I'll try to have a look after Christmas!
