### ISSUE TITLE
Entries with value "null" get imported

### ISSUE THREAD

**Issue by systemoperator** [JabRef/JabRef-Browser-Extension#123]
When creating a reference of e.g. [https://ieeexplore.ieee.org/document/8482125](url), the resulting reference entry in JabRef contains among others `null` values (all unrelevant entries have been omitted):

```
@InProceedings{Sychev2018,
  note      = {ISSN: null},
  issn      = {null},
}
```

**Comment by tobiasdiez** [comment]
The provided link currently fails with
> Translation using IEEE Xplore failed: 
HTTP POST https://ieeexplore.ieee.org/xpl/downloadCitations failed with status code 503
url => https://ieeexplore.ieee.org/document/8482125

I guess this is due to the recent api change of IEEE and is definitely a problem with the JabRef browser extension. Can you please report this issue over at zotero/translators. Thanks!
