### ISSUE TITLE
JabRef on firefox don't support capturing PDF links

### ISSUE THREAD

**Issue by OmarElAshkar** [JabRef/JabRef-Browser-Extension#244]
Hello,
On JabRef firefox extension, it seems like the extension does not support directly adding a pdf file like in this link:

[testpaper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3123451/pdf/nihms288491.pdf)

I suggest if it's possible, to create a dummy entery with the name of the pdf as the title temporarly, then update from the metadata of the pdf.

Best Regards,
Omar

**Comment by wwtan** [comment]
Hi,

I have the same issue over [here](https://journals.sagepub.com/doi/full/10.1177/0954410015591045). The html page is downloaded instead of the actual pdf after I have entered my credentials.

Thanks and best wishes,
Weijie

Running Firefox 84.0.2, JabRef 5.2, Browser extension 2.2

**Comment by tobiasdiez** [comment]
This should be fixed in the next release. Then you also have a JabRef icon when a PDFs is displayed. As of now the extracted metadata is pretty limited, since we cannot get any data from the website. Thus it is still recommended to go the article webpage.

@wwtan This should be a problem with the specific translator used (which is not able to correctly resolve the PDF). Please open a issue for this at https://github.com/zotero/translators. Thanks!

**Comment by adam3smith** [comment]
@tobiasdiez it's great that JabRef is using Zotero translators, but please don't ask people to open issues on the Zotero translator github unless they've actually looked at the code and identified specific issues. 
The majority of import/translation issues is not due to actual translator problems and we do all triage for translators on forums.zotero.org (and will require people to actually run Zotero and run through https://www.zotero.org/support/troubleshooting_translator_issues -- no way we can test with another suite of software given the number of moving parts)

**Comment by tobiasdiez** [comment]
@adam3smith Sure! I wasn't aware of this specific site for translator issues. Will point people to it in the future!
