### ISSUE TITLE
JabRef Chrome / Edge Extension NOT Working! Error while sending to JabRef. 

### ISSUE THREAD

**Issue by zhangzw16** [JabRef/JabRef-Browser-Extension#304]
Here's the problem:
Not matter on which site I open JabRef extension, it always shows **"Error while sending to JabRef. Please see the browsers error console for details."**

![Screen Shot 2021-04-21 at 11 01 31 AM](https://user-images.githubusercontent.com/26004183/115490582-f25b6b80-a290-11eb-98ef-d694285514b3.png)

And in Devtools, the console shows
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://bifehkofibaamoeaopjglfkddgkijdlh/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

It is always the case, whether in any Google scholar website or arxiv website. Google Chrome and Microsoft Edge both seem to have this problem. Any idea how to fix it? THX!

**Comment by tobiasdiez** [comment]
Are there more error messages in the devtools console? The above is only an unrelated warning.

Since you experience these problems in edge and chrome, this points to a problem with the jabref setup. You can try the manual setup steps described at https://docs.jabref.org/collect/jabref-browser-extension

**Comment by zhangzw16** [comment]
This is the only error/warning that the devtools console outputs.
<img width="1000" alt="Screen Shot 2021-04-21 at 6 59 12 PM" src="https://user-images.githubusercontent.com/26004183/115543224-b4cc0200-a2d3-11eb-84c3-e9845ddde06f.png">
After following the instructions on [this website](https://docs.jabref.org/collect/jabref-browser-extension), the extension seems work fine. It recognizes arxiv website but keeps **searching for Bibliographic data ...** for Google Scholar website. Don't know if its because bad internet or not.

To be more clear, I made the following changes(just for Google Chrome, and actually I don't know if both steps are necessary):

1. download org.jabref.jabref.json and modify the existing file `/Library/Google/Chrome/NativeMessagingHosts/org.jabref.jabref.json` to the content of downloading file.
2. put the download json file into `~/Library/Application Support/Google/Chrome/NativeMessagingHosts/org.jabref.jabref.json`, which doesn't exist previously.

Note that: the file path in the "admin" case is different from the website(my macOS version is version 11.2.1).

**Comment by tobiasdiez** [comment]
I'm glad it is working for you now. Google scholar often doesn't work because they have a very very strict quote of calls that they admit to their api, and you usually hit this limit already after one or two searches. Sadly, nothing we can improve.

@LyzardKing is there a problem in our mac install scripts that the json file is not copied into the correct path? (step 2 above)

**Comment by LyzardKing** [comment]
I haven't tested the automatic install script (it only works in the pkg) since I'm not running macos.

The path on the website now only works for chromium, not chrome.
We need to add the new path (the one @zhangzw16 used).
I'll open a PR on the repo.

The fact that the user folder does not exist is normal, since it isn't created automaticaly

**Comment by tobiasdiez** [comment]
Thanks a lot @LyzardKing, and thanks @zhangzw16 for sharing your solution.

Since the issue seems to be resolved now, I'll close it.
