### ISSUE TITLE
JABREF Chrome extension only works on some sites:

### ISSUE THREAD

**Issue by ManjuO** [JabRef/JabRef-Browser-Extension#374]
When the JABREF desktop app is closed, the Chrome extension works as it should, sometimes. For many websites, it look like this: 
![image](https://user-images.githubusercontent.com/63151192/139808598-54fcbeaa-d059-4883-b5df-0ee80b870abd.png
![Snag_5a9d29f0](https://user-images.githubusercontent.com/63151192/139808659-454ecb69-0700-4cae-bf2c-98b66ec4ab91.png)
)

Here is an example link that was not working: https://www.eumofa.eu/documents/20178/367933/PTAT_Organic%20salmon.pdf

I've tried it on many sites and have resorted to another biblatex text converter, which I have to copy and paste and fix.

Even though it was connected to JabRef, I went through the extension instructions and added the (without host in name) files not there. But when I pointed the JabRefHost.ps1 part to the JabRef.bat file, it stopped connecting, so I kept the original file. I don't code and probably did it wrong, but I think the ps1 file was already pointing to the correct folder. Here is an image of the folder contents:
![Snag_5aa3c671](https://user-images.githubusercontent.com/63151192/139809520-e71c0315-bd92-4bff-a559-ba1144da2380.png)

**Comment by tobiasdiez** [comment]
The extension sadly doesn't work for PDF files. On one hand, it's very hard to extract metadata from pdfs and on the other hand browser put the pdf reader in a special sandbox so that browser extensions cannot interact with it. So sadly nothing we can do here.

What usually works is to import the website that links to the pdf (e.g. the journal website).
