### ISSUE TITLE
Every word of title is protected in imported records

### ISSUE THREAD

**Issue by jelasity** [JabRef/JabRef-Browser-Extension#439]
Hi, I realized that in entries imported using the web browser plugin, every word of the title is protected to preserve "title case" capitalization. This is incorrect behavior, because the capitalization of the title is defined by bibtex styles. Only specific words should to be protected such as proper names.

I was not able to find any possibility to switch this behavior off (eg in preferences, or somewhere). How can I prevent jabref from protecting every word of the title?

Thanks: Mark

JabRef 5.3--2021-07-05--bed9ac9
Linux 5.12.13-1-default amd64 
Java 16.0.1 
plugin version: 2.4

**Comment by Siedlerchr** [comment]
I just transferred this issue to the Browser Extension repo. I encountered the same annoying behavior recently

**Comment by tobiasdiez** [comment]
Can you please give a concrete example where this happens?

**Comment by Siedlerchr** [comment]
Example from Firefox:
https://revista.unap.ro/index.php/XXI_FSA/article/view/1260

Every word is in upper case in JabRef enclosed in protected terms braces and therefore the Cleanup will not modify the casing.

results in:
```
@Article{Preda2021,
  author    = {Preda, Alin},
  journal   = {STRATEGIES XXI - Security and Defense Faculty},
  title     = {{SOCIAL} {MEDIA} {IN} {INFORMATION} {WARFARE}. {ASSAULT} {WEAPON} {WITH} {HIGH} {RECOIL}},
  year      = {2021},
  issn      = {2668-2001},
}
```

**Comment by mlep** [comment]
Adding the field formatter "Unprotect terms" for the field name "Title" removes the braces. 
And adding the field formatter "Title case" arranges the casing.

JabRef 5.5--2022-01-17--27a05c7

**Comment by nujabse** [comment]
Having the same issue on JabRef 5.6. Hope there can be an option to cancel the protect words feature.

**Comment by tobiasdiez** [comment]
This is more an issue with the journal website than Zotero/the browser extension. The website contains
```
<meta name="citation_title" content="SOCIAL MEDIA IN INFORMATION WARFARE. ASSAULT WEAPON WITH HIGH RECOIL ">
```
Every word in the title is in caps, thus for zotero/the browser extension it appears that every word is an acronym, which should be exported in bibtex by surrounding it with braces. So the code works as expected. Please contact the journal to correct the metadata, otherwise there is not much we can do. Moreover, the workaround mentioned above by mlep with running the field formatter works as well, so closing.
