### ISSUE TITLE
Unknown error while sending to JabRef. Error: Error when communicating with the native messaging host. at chrome-extension://bifehkofibaamoeaopjglfkddgkijdlh/browser-polyfill.min.js:1:6365

### ISSUE THREAD

**Issue by egen97** [JabRef/JabRef-Browser-Extension#533]
Get this message when attempting to import a reference. Tried to do the manual install of the browser-pluging with HKEY_CURRENT_USER, as well as making JabRef listen for remote operations on the standard port (6050). 
Using Windows 10, Chrome Versjon 108.0.5359.125 (Offisiell delversjon) (64-bit)

**Comment by tobiasdiez** [comment]
This is sadly the most generic error message that chrome sends "when something goes wrong", so very hard to debug remotely. Previously, a similar issue https://github.com/JabRef/JabRef-Browser-Extension/issues/493 was fixed by upgrading JabRef to the latest version - but sadly not for everyone. Let's continue the discussion there, and I would like to ask you to try https://github.com/JabRef/JabRef-Browser-Extension/issues/493#issuecomment-1266677443.
